version: '3.8'

services:
  app:
    image: node:18-bullseye-slim
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CI_COMMIT_SHA=${CI_COMMIT_SHA}
    volumes:
      - ./:/usr/server/app
    command: npm run start